# Generated by Django 5.1.1 on 2024-09-07 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique ID associated with the item', unique=True)),
                ('location_id', models.TextField(help_text='Location ID associated with the item')),
                ('item_type', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('GAMES', 'Games'), ('ARTS', 'Arts'), ('MEN_FASHION', 'Men_fashion'), ('WOMEN_FASHION', 'Women_fashion')], help_text='Type of item dropped off', max_length=15)),
                ('image_path', models.TextField(help_text='Path to the image location in the cloud bucket')),
                ('list_time', models.DateTimeField(auto_now=True, help_text='The time that the item was listed')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], help_text='The status of the item', max_length=15)),
                ('item_name', models.CharField(help_text='The name of the item', max_length=100)),
                ('item_description', models.TextField(help_text='A description of the item')),
                ('user_id', models.ForeignKey(help_text='The user id who dropped off the item', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
