# Generated by Django 5.1.1 on 2024-09-07 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, help_text='A unique ID associated with the item', unique=True)),
                ('location_id', models.TextField()),
                ('item_type', models.CharField(choices=[('SOCKS', 'socks'), ('PADS', 'pads'), ('UNDERWEAR', 'underwear')], help_text='Type of item dropped off', max_length=15)),
                ('image_path', models.TextField(help_text='Path the image location in cloud bucket')),
                ('list_time', models.DateTimeField(auto_now=True, help_text='The time that the item was listed')),
            ],
        ),
    ]
