# Generated by Django 5.1.1 on 2024-09-07 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='description', help_text='A description of the item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='item', help_text='The name of the item', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', help_text='The status of the item', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image_path',
            field=models.TextField(help_text='Path to the image location in the cloud bucket'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique ID associated with the item', unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('GAMES', 'Games'), ('ARTS', 'Arts'), ('MEN_FASHION', 'Men_fashion'), ('WOMEN_FASHION', 'Women_fashion')], help_text='Type of item dropped off', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='location_id',
            field=models.TextField(help_text='Location ID associated with the item'),
        ),
    ]
